# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.kernelModules = [ "kvm-intel" "wl" ];
  boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];
  boot.blacklistedKernelModules = [ "bcma" ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/21fae3c0-9aea-407b-b86a-54eae816c55a";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/88C7-745A";
      fsType = "vfat";
    };

  fileSystems."/home/dima/backup" =
    { device = "/dev/disk/by-uuid/486888ea-b9fd-4b5e-931b-817019019bba";
      fsType = "btrfs";
    };

  fileSystems."/home/dima/backup2" =
    { device = "/dev/disk/by-uuid/88c220d4-a886-4c2c-b4a2-33df11d89332";
      fsType = "btrfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/83620877-7f22-4aa9-b413-d0f9135d2b93"; }
    ];

  nix.maxJobs = lib.mkDefault 8;
}
