# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.kernelModules = [ "kvm-amd" "wl" ];
  boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];

  fileSystems."/" =
    { device = "mypool/root/nixos";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "mypool/root/home";
      fsType = "zfs";
    };

  fileSystems."/tmp" =
    { device = "mypool/root/tmp";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/md127";
      fsType = "ext4";
    };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 32;
}
